'use strict';
const $=s=>document.querySelector(s), enc=new TextEncoder(), dec=new TextDecoder();
let project=null, progress=null, xsdBytes=null, mode='mark', selected=null, scale=1, tx=12, ty=12, pointers=new Map(), gesture=null, history=[], session=null;
const key=(x,y)=>`${x},${y}`, toast=m=>{let e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)};

function db(){return new Promise((ok,no)=>{let r=indexedDB.open('stitchy-mobile',1);r.onupgradeneeded=()=>r.result.createObjectStore('projects',{keyPath:'id'});r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function put(value){let d=await db();return new Promise((ok,no)=>{let t=d.transaction('projects','readwrite');t.objectStore('projects').put(value);t.oncomplete=ok;t.onerror=()=>no(t.error)})}
async function all(){let d=await db();return new Promise((ok,no)=>{let r=d.transaction('projects').objectStore('projects').getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function save(){if(!project)return;await put({id:project.id,title:project.metadata?.title||project.id,pattern:project,progress,xsdBytes,updated:Date.now()});drawLibrary()}

function u16(a,o){return a[o]|a[o+1]<<8} function u32(a,o){return (a[o]|a[o+1]<<8|a[o+2]<<16|a[o+3]<<24)>>>0}
async function unzip(buffer){let a=new Uint8Array(buffer),end=-1;for(let i=a.length-22;i>=Math.max(0,a.length-65557);i--)if(u32(a,i)===0x06054b50){end=i;break}if(end<0)throw Error('Not a ZIP file');let count=u16(a,end+10),off=u32(a,end+16),out={};for(let n=0;n<count;n++){if(u32(a,off)!==0x02014b50)throw Error('Damaged ZIP directory');let method=u16(a,off+10),size=u32(a,off+20),nameLen=u16(a,off+28),extra=u16(a,off+30),comment=u16(a,off+32),local=u32(a,off+42),name=dec.decode(a.slice(off+46,off+46+nameLen)),ln=u16(a,local+26),le=u16(a,local+28),bytes=a.slice(local+30+ln+le,local+30+ln+le+size);if(method===8){if(!('DecompressionStream'in window))throw Error('This Safari version cannot decompress backups');let stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate-raw'));bytes=new Uint8Array(await new Response(stream).arrayBuffer())}else if(method!==0)throw Error('Unsupported ZIP compression');out[name]=bytes;off+=46+nameLen+extra+comment}return out}
function crc32(a){let c=-1;for(let b of a){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^-1)>>>0}
function zip(files){let local=[],central=[],offset=0;for(let [name,data] of Object.entries(files)){let nb=enc.encode(name),a=data instanceof Uint8Array?data:enc.encode(data),crc=crc32(a),h=new Uint8Array(30+nb.length+a.length),v=new DataView(h.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint32(14,crc,true);v.setUint32(18,a.length,true);v.setUint32(22,a.length,true);v.setUint16(26,nb.length,true);h.set(nb,30);h.set(a,30+nb.length);local.push(h);let c=new Uint8Array(46+nb.length),cv=new DataView(c.buffer);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint32(16,crc,true);cv.setUint32(20,a.length,true);cv.setUint32(24,a.length,true);cv.setUint16(28,nb.length,true);cv.setUint32(42,offset,true);c.set(nb,46);central.push(c);offset+=h.length}let cs=central.reduce((n,a)=>n+a.length,0),e=new Uint8Array(22),ev=new DataView(e.buffer);ev.setUint32(0,0x06054b50,true);ev.setUint16(8,central.length,true);ev.setUint16(10,central.length,true);ev.setUint32(12,cs,true);ev.setUint32(16,offset,true);return new Blob([...local,...central,e],{type:'application/zip'})}

async function importFile(file){try{let files=await unzip(await file.arrayBuffer());if(!files['pattern.json'])throw Error('This backup was made by an older Stitchy. Re-export it from the updated Mac app.');project=JSON.parse(dec.decode(files['pattern.json']));progress=files['progress.json']?JSON.parse(dec.decode(files['progress.json'])):{};xsdBytes=files['pattern.xsd']||null;project.id=(project.metadata?.title||file.name).replace(/[^\w-]+/g,'-')+'-'+Date.now();normalise();await save();openWorkspace()}catch(e){toast(e.message)}}
function normalise(){progress={completed:[],parked:{},notes:{},history:[],started_at:new Date().toISOString(),...progress};progress.completed=[...new Set(progress.completed)];}
async function drawLibrary(){let rows=await all(),html=rows.sort((a,b)=>b.updated-a.updated).map(p=>`<button class="project" data-id="${p.id}"><b>${escapeHtml(p.title)}</b><span>${new Date(p.updated).toLocaleDateString()}</span></button>`).join('');$('#projects').innerHTML=html||'<p>No imported projects yet.</p>';$('#libraryList').innerHTML=html||'<p>No projects yet.</p>';document.querySelectorAll('.project').forEach(b=>b.onclick=async()=>{let p=(await all()).find(x=>x.id===b.dataset.id);project=p.pattern;progress=p.progress;xsdBytes=p.xsdBytes||null;normalise();$('#library').close();openWorkspace()})}
const escapeHtml=s=>String(s||'Untitled').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function openWorkspace(){$('#home').hidden=true;$('#workspace').hidden=false;$('#subtitle').textContent=project.metadata?.title||'Pattern';selected=null;fit();render();drawPalette();updateStatus()}
function occupied(){let m=new Map;for(let s of project.full)m.set(key(s[0],s[1]),s[2]);for(let s of project.part)m.set(key(Math.floor(s[0]/2),Math.floor(s[1]/2)),s[2]);return m}
function render(){let c=$('#chart'),cell=12,dpr=devicePixelRatio||1;c.width=project.width*cell*dpr;c.height=project.height*cell*dpr;c.style.width=project.width*cell+'px';c.style.height=project.height*cell+'px';c.style.transform=`translate(${tx}px,${ty}px) scale(${scale})`;let g=c.getContext('2d');g.scale(dpr,dpr);g.fillStyle='#fff';g.fillRect(0,0,c.width,c.height);let done=new Set(progress.completed);for(let s of project.full){let x=s[0]*cell,y=s[1]*cell,i=s[2],dim=selected!=null&&selected!==i;g.globalAlpha=dim?.1:1;g.fillStyle=project.palette[i]?.color||'#f0f';g.fillRect(x,y,cell,cell);if(done.has(key(s[0],s[1]))){g.globalAlpha=.72;g.fillStyle='#fff';g.fillRect(x,y,cell,cell);g.globalAlpha=1;g.strokeStyle='#287a4a';g.lineWidth=2;g.beginPath();g.moveTo(x+2,y+6);g.lineTo(x+5,y+9);g.lineTo(x+10,y+2);g.stroke()}}g.globalAlpha=1;g.lineWidth=.45;g.strokeStyle='#bbb';for(let x=0;x<=project.width;x++){g.beginPath();g.moveTo(x*cell,0);g.lineTo(x*cell,project.height*cell);g.stroke()}for(let y=0;y<=project.height;y++){g.beginPath();g.moveTo(0,y*cell);g.lineTo(project.width*cell,y*cell);g.stroke()}g.strokeStyle='#555';g.lineWidth=1.2;for(let x=0;x<=project.width;x+=10){g.beginPath();g.moveTo(x*cell,0);g.lineTo(x*cell,project.height*cell);g.stroke()}for(let y=0;y<=project.height;y+=10){g.beginPath();g.moveTo(0,y*cell);g.lineTo(project.width*cell,y*cell);g.stroke()}for(let [k] of Object.entries(progress.parked||{})){let[x,y]=k.split(',').map(Number);g.fillStyle='#111';g.beginPath();g.moveTo(x*cell,y*cell);g.lineTo(x*cell+7,y*cell);g.lineTo(x*cell,y*cell+7);g.fill()}for(let k of Object.keys(progress.notes||{})){let[x,y]=k.split(',').map(Number);g.fillStyle='#d9799a';g.beginPath();g.arc(x*cell+9,y*cell+3,2.5,0,7);g.fill()}}
function fit(){let v=$('#viewport'),cell=12;scale=Math.min((v.clientWidth-24)/(project.width*cell),(v.clientHeight-24)/(project.height*cell),2);tx=(v.clientWidth-project.width*cell*scale)/2;ty=(v.clientHeight-project.height*cell*scale)/2;render()}
function chartCell(clientX,clientY){let r=$('#chart').getBoundingClientRect();return{x:Math.floor((clientX-r.left)/r.width*project.width),y:Math.floor((clientY-r.top)/r.height*project.height)}}
async function act(x,y){if(x<0||y<0||x>=project.width||y>=project.height)return;let map=occupied(),k=key(x,y),i=map.get(k);if(i==null){toast('No cross stitch here');return}if(mode==='mark'){history.push([...progress.completed]);let set=new Set(progress.completed);set.has(k)?set.delete(k):set.add(k);progress.completed=[...set]}else if(mode==='select'){selected=selected===i?null:i;drawPalette()}else if(mode==='park'){progress.parked[k]==null?progress.parked[k]=i:delete progress.parked[k]}else if(mode==='note'){let text=prompt('Note for this stitch:',progress.notes[k]||'');if(text!==null){text.trim()?progress.notes[k]=text.trim():delete progress.notes[k]}}await save();render();updateStatus()}
function updateStatus(){let total=occupied().size,done=progress.completed.length,pct=total?Math.round(done/total*100):0;$('#percent').textContent=pct+'%';$('#counts').textContent=`${done.toLocaleString()} of ${total.toLocaleString()} · ${(total-done).toLocaleString()} left`}
function drawPalette(){$('#palette').innerHTML=project.palette.map(p=>`<div class="thread ${selected===p.index?'on':''}" data-i="${p.index}"><span class="sw" style="background:${p.color}"></span><span><b>${escapeHtml(p.label)}</b><br>${project.full.filter(s=>s[2]===p.index).length.toLocaleString()} crosses</span></div>`).join('');document.querySelectorAll('.thread').forEach(e=>e.onclick=()=>{selected=+e.dataset.i;render();drawPalette()})}

$('#file').onchange=e=>e.target.files[0]&&importFile(e.target.files[0]);$('#fit').onclick=fit;$('#clearColor').onclick=()=>{selected=null;render();drawPalette()};$('#undo').onclick=async()=>{if(history.length){progress.completed=history.pop();await save();render();updateStatus()}};$('#libraryBtn').onclick=()=>$('#library').showModal();
$('#demo').onclick=async()=>{let response=await fetch('demo/stitchy-bunny.stitchy.zip');await importFile(new File([await response.blob()],'stitchy-bunny.stitchy.zip'))};
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('on',x===b));$('#palette').style.display=mode==='select'?'block':''});
$('#export').onclick=()=>{let name=(project.metadata?.title||'pattern')+'.xsd',manifest=JSON.stringify({format:'stitchy-project',version:1,pattern:name,progress:'progress.json'}),files={'manifest.json':manifest,'pattern.json':JSON.stringify(project),'progress.json':JSON.stringify(progress)};if(xsdBytes)files['pattern.xsd']=xsdBytes;let blob=zip(files),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(project.metadata?.title||'Stitchy')+'.stitchy.zip';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('#session').onclick=async()=>{if(!session){session={start:Date.now()};document.body.classList.add('session');navigator.wakeLock?.request('screen').then(x=>session&&(session.lock=x)).catch(()=>{});$('#session').textContent='End session';session.timer=setInterval(()=>{$('#clock').textContent=new Date(Date.now()-session.start).toISOString().slice(11,19)},1000)}else{clearInterval(session.timer);session.lock?.release();session=null;document.body.classList.remove('session');$('#session').textContent='Stitch mode';$('#clock').textContent=''}};
let v=$('#viewport');v.onpointerdown=e=>{v.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){let p=[...pointers.values()];gesture={distance:Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y),scale,tx,ty,cx:(p[0].x+p[1].x)/2,cy:(p[0].y+p[1].y)/2}}};v.onpointermove=e=>{if(!pointers.has(e.pointerId))return;let old=pointers.get(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2&&gesture){let p=[...pointers.values()],ratio=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y)/gesture.distance,next=Math.max(.15,Math.min(8,gesture.scale*ratio));tx=gesture.cx-(gesture.cx-gesture.tx)*next/gesture.scale;ty=gesture.cy-(gesture.cy-gesture.ty)*next/gesture.scale;scale=next;render()}else if(pointers.size===1){tx+=e.clientX-old.x;ty+=e.clientY-old.y;render()}};v.onpointerup=e=>{let start=pointers.get(e.pointerId);if(pointers.size===1&&start&&Math.hypot(e.clientX-start.x,e.clientY-start.y)<8){let p=chartCell(e.clientX,e.clientY);act(p.x,p.y)}pointers.delete(e.pointerId);if(pointers.size<2)gesture=null};v.onpointercancel=e=>{pointers.delete(e.pointerId);gesture=null};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');drawLibrary();
