'use strict';
const $=s=>document.querySelector(s), enc=new TextEncoder(), dec=new TextDecoder();
let project=null, progress=null, xsdBytes=null, mode='mark', selected=null, colorPanelOpen=false, colorPick=false, showSymbols=true, showBackstitch=true, scale=1, tx=12, ty=12, pointers=new Map(), gesture=null, history=[], session=null;
const key=(x,y)=>`${x},${y}`, toast=m=>{let e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)};

function db(){return new Promise((ok,no)=>{let r=indexedDB.open('stitchy-mobile',1);r.onupgradeneeded=()=>r.result.createObjectStore('projects',{keyPath:'id'});r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function put(value){let d=await db();return new Promise((ok,no)=>{let t=d.transaction('projects','readwrite');t.objectStore('projects').put(value);t.oncomplete=ok;t.onerror=()=>no(t.error)})}
async function all(){let d=await db();return new Promise((ok,no)=>{let r=d.transaction('projects').objectStore('projects').getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function save(){if(!project)return;await put({id:project.id,title:project.metadata?.title||project.id,pattern:project,progress,xsdBytes,updated:Date.now()});drawLibrary()}

function u16(a,o){return a[o]|a[o+1]<<8} function u32(a,o){return (a[o]|a[o+1]<<8|a[o+2]<<16|a[o+3]<<24)>>>0}
async function unzip(buffer){let a=new Uint8Array(buffer),end=-1;for(let i=a.length-22;i>=Math.max(0,a.length-65557);i--)if(u32(a,i)===0x06054b50){end=i;break}if(end<0)throw Error('Not a ZIP file');let count=u16(a,end+10),off=u32(a,end+16),out={};for(let n=0;n<count;n++){if(u32(a,off)!==0x02014b50)throw Error('Damaged ZIP directory');let method=u16(a,off+10),size=u32(a,off+20),nameLen=u16(a,off+28),extra=u16(a,off+30),comment=u16(a,off+32),local=u32(a,off+42),name=dec.decode(a.slice(off+46,off+46+nameLen)),ln=u16(a,local+26),le=u16(a,local+28),bytes=a.slice(local+30+ln+le,local+30+ln+le+size);if(method===8){if(!('DecompressionStream'in window))throw Error('This Safari version cannot decompress backups');let stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate-raw'));bytes=new Uint8Array(await new Response(stream).arrayBuffer())}else if(method!==0)throw Error('Unsupported ZIP compression');out[name]=bytes;off+=46+nameLen+extra+comment}return out}
function crc32(a){let c=-1;for(let b of a){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^-1)>>>0}
function zip(files){let local=[],central=[],offset=0;for(let [name,data] of Object.entries(files)){let nb=enc.encode(name),a=data instanceof Uint8Array?data:enc.encode(data),crc=crc32(a),h=new Uint8Array(30+nb.length+a.length),v=new DataView(h.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint32(14,crc,true);v.setUint32(18,a.length,true);v.setUint32(22,a.length,true);v.setUint16(26,nb.length,true);h.set(nb,30);h.set(a,30+nb.length);local.push(h);let c=new Uint8Array(46+nb.length),cv=new DataView(c.buffer);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint32(16,crc,true);cv.setUint32(20,a.length,true);cv.setUint32(24,a.length,true);cv.setUint16(28,nb.length,true);cv.setUint32(42,offset,true);c.set(nb,46);central.push(c);offset+=h.length}let cs=central.reduce((n,a)=>n+a.length,0),e=new Uint8Array(22),ev=new DataView(e.buffer);ev.setUint32(0,0x06054b50,true);ev.setUint16(8,central.length,true);ev.setUint16(10,central.length,true);ev.setUint32(12,cs,true);ev.setUint32(16,offset,true);return new Blob([...local,...central,e],{type:'application/zip'})}

async function importFile(file){try{let files=await unzip(await file.arrayBuffer());if(!files['pattern.json'])throw Error('This backup was made by an older Stitchy. Re-export it from the updated Mac app.');project=JSON.parse(dec.decode(files['pattern.json']));progress=files['progress.json']?JSON.parse(dec.decode(files['progress.json'])):{};xsdBytes=files['pattern.xsd']||null;project.id=(project.metadata?.title||file.name).replace(/[^\w-]+/g,'-')+'-'+Date.now();normalise();await save();openWorkspace();return true}catch(e){toast(e.message);return false}}
function normalise(){progress={completed:[],parked:{},notes:{},history:[],started_at:new Date().toISOString(),...progress};progress.completed=[...new Set(progress.completed)];}
const isBunnyDemo=p=>p?.title==='Stitchy Bunny'&&p?.pattern?.metadata?.author==='Stitchy';
function bestBunny(rows){return rows.filter(isBunnyDemo).sort((a,b)=>(b.progress?.completed?.length||0)-(a.progress?.completed?.length||0)||b.updated-a.updated)[0]}
function visibleProjects(rows){let bunny=bestBunny(rows),shown=false;return rows.sort((a,b)=>b.updated-a.updated).filter(p=>!isBunnyDemo(p)||(p.id===bunny?.id&&!shown&&(shown=true)))}
async function drawLibrary(){let rows=visibleProjects(await all()),html=rows.map(p=>`<button class="project" data-id="${p.id}"><b>${escapeHtml(p.title)}</b><span>${new Date(p.updated).toLocaleDateString()}</span></button>`).join('');$('#projects').innerHTML=html||'<p>No imported projects yet.</p>';$('#libraryList').innerHTML=html||'<p>No projects yet.</p>';document.querySelectorAll('.project').forEach(b=>b.onclick=async()=>{let p=(await all()).find(x=>x.id===b.dataset.id);project=p.pattern;progress=p.progress;xsdBytes=p.xsdBytes||null;normalise();$('#library').close();openWorkspace()})}
const escapeHtml=s=>String(s||'Untitled').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function openWorkspace(){$('#home').hidden=true;$('#workspace').hidden=false;$('#homeBtn').hidden=false;$('#subtitle').textContent=project.metadata?.title||'Pattern';selected=null;colorPanelOpen=false;colorPick=false;mode='mark';document.querySelectorAll('[data-tool]').forEach(x=>{let on=x.dataset.tool==='mark';x.classList.toggle('on',on);x.setAttribute('aria-pressed',on)});$('#colorPicker').classList.remove('on');fit();render();drawPalette();updateStatus()}
function goHome(){$('#workspace').hidden=true;$('#home').hidden=false;$('#homeBtn').hidden=true;$('#subtitle').textContent='Mobile stitching companion';drawLibrary()}
function occupied(){let m=new Map;for(let s of project.full)m.set(key(s[0],s[1]),s[2]);for(let s of project.part)m.set(key(Math.floor(s[0]/2),Math.floor(s[1]/2)),s[2]);return m}
function selectedRuns(){if(selected==null)return[];let rows=new Map;for(let [x,y,i] of project.full)if(i===selected){if(!rows.has(y))rows.set(y,[]);rows.get(y).push(x)}let runs=[];for(let [y,xs] of rows){xs.sort((a,b)=>a-b);let start=xs[0],last=xs[0];for(let n=1;n<=xs.length;n++){let x=xs[n];if(x!==last+1){let length=last-start+1;if(length>1)runs.push({y,start,end:last,length});start=x}last=x}}return runs}
function runBadgeAt(clientX,clientY){if(selected==null)return null;let r=$('#chart').getBoundingClientRect(),px=(clientX-r.left)/r.width*project.width*12,py=(clientY-r.top)/r.height*project.height*12;return selectedRuns().find(run=>{let cx=(run.start+run.end+1)*6,cy=(run.y+.5)*12,bw=Math.max(12,String(run.length).length*5+6);return Math.abs(px-cx)<=bw/2+2&&Math.abs(py-cy)<=7})||null}
function symbolFor(i){return project.palette[i]?.symbol||String(i+1)}
function symbolInk(hex){let h=(hex||'#ffffff').replace('#',''),r=parseInt(h.slice(0,2),16)||0,g=parseInt(h.slice(2,4),16)||0,b=parseInt(h.slice(4,6),16)||0;return .299*r+.587*g+.114*b>145?'#171311cc':'#ffffffde'}
function render(){
  let c=$('#chart'),cell=12,dpr=devicePixelRatio||1,w=project.width*cell,h=project.height*cell;
  c.width=w*dpr;c.height=h*dpr;c.style.width=w+'px';c.style.height=h+'px';c.style.transform=`translate(${tx}px,${ty}px) scale(${scale})`;
  let g=c.getContext('2d');g.scale(dpr,dpr);g.fillStyle='#fff';g.fillRect(0,0,w,h);let done=new Set(progress.completed);
  for(let s of project.full){let x=s[0]*cell,y=s[1]*cell,i=s[2],color=project.palette[i]?.color||'#f0f',dim=selected!=null&&selected!==i;g.globalAlpha=dim?.1:1;g.fillStyle=color;g.fillRect(x,y,cell,cell);if(showSymbols){g.fillStyle=symbolInk(color);g.font=`bold ${symbolFor(i).length>1?6.5:8.5}px ui-monospace,SFMono-Regular,Menlo,monospace`;g.textAlign='center';g.textBaseline='middle';g.fillText(symbolFor(i),x+cell/2,y+cell/2+.3)}if(done.has(key(s[0],s[1]))){g.globalAlpha=.72;g.fillStyle='#fff';g.fillRect(x,y,cell,cell);g.globalAlpha=dim?.1:1;g.strokeStyle='#287a4a';g.lineWidth=2;g.beginPath();g.moveTo(x+2,y+6);g.lineTo(x+5,y+9);g.lineTo(x+10,y+2);g.stroke()}}
  for(let s of project.part||[]){let x=s[0]/2*cell,y=s[1]/2*cell,i=s[2],back=s[4]==='backward',dim=selected!=null&&selected!==i;g.globalAlpha=dim?.1:1;g.fillStyle=project.palette[i]?.color||'#f0f';g.beginPath();g.moveTo(x,y);if(back){g.lineTo(x+cell,y);g.lineTo(x+cell,y+cell)}else{g.lineTo(x+cell,y+cell);g.lineTo(x,y+cell)}g.closePath();g.fill()}
  g.globalAlpha=1;g.lineWidth=.45;g.strokeStyle='#bbb';for(let x=0;x<=project.width;x++){g.beginPath();g.moveTo(x*cell,0);g.lineTo(x*cell,h);g.stroke()}for(let y=0;y<=project.height;y++){g.beginPath();g.moveTo(0,y*cell);g.lineTo(w,y*cell);g.stroke()}g.strokeStyle='#555';g.lineWidth=1.2;for(let x=0;x<=project.width;x+=10){g.beginPath();g.moveTo(x*cell,0);g.lineTo(x*cell,h);g.stroke()}for(let y=0;y<=project.height;y+=10){g.beginPath();g.moveTo(0,y*cell);g.lineTo(w,y*cell);g.stroke()}
  if(showBackstitch)for(let s of project.lines||[]){let i=s[4],dim=selected!=null&&selected!==i;g.globalAlpha=dim?.1:1;g.strokeStyle=project.palette[i]?.color||'#111';g.lineWidth=1.8;g.lineCap='round';g.beginPath();g.moveTo(s[0]/2*cell,s[1]/2*cell);g.lineTo(s[2]/2*cell,s[3]/2*cell);g.stroke()}
  for(let s of project.nodes||[]){let i=s[2],dim=selected!=null&&selected!==i;g.globalAlpha=dim?.1:1;g.fillStyle=project.palette[i]?.color||'#111';g.strokeStyle='#0008';g.lineWidth=.5;g.beginPath();g.arc(s[0]/2*cell,s[1]/2*cell,s[3]==='bead'?2.8:2.2,0,7);g.fill();g.stroke()}
  g.globalAlpha=1;for(let [k] of Object.entries(progress.parked||{})){let[x,y]=k.split(',').map(Number);g.fillStyle='#111';g.beginPath();g.moveTo(x*cell,y*cell);g.lineTo(x*cell+7,y*cell);g.lineTo(x*cell,y*cell+7);g.fill()}for(let k of Object.keys(progress.notes||{})){let[x,y]=k.split(',').map(Number);g.fillStyle='#d9799a';g.beginPath();g.arc(x*cell+9,y*cell+3,2.5,0,7);g.fill()}
  if(selected!=null){g.font='bold 8px -apple-system,BlinkMacSystemFont,sans-serif';g.textAlign='center';g.textBaseline='middle';for(let run of selectedRuns()){let cx=(run.start+run.end+1)*cell/2,cy=(run.y+.5)*cell,label=String(run.length),bw=Math.max(12,g.measureText(label).width+6);g.fillStyle='#fff';g.strokeStyle='#2f2926';g.lineWidth=1;g.beginPath();g.roundRect(cx-bw/2,cy-5,bw,10,4);g.fill();g.stroke();g.fillStyle='#2f2926';g.fillText(label,cx,cy+.25)}}
}
function fit(){let v=$('#viewport'),cell=12;scale=Math.min((v.clientWidth-24)/(project.width*cell),(v.clientHeight-24)/(project.height*cell),2);tx=(v.clientWidth-project.width*cell*scale)/2;ty=(v.clientHeight-project.height*cell*scale)/2;render()}
function chartCell(clientX,clientY){let r=$('#chart').getBoundingClientRect();return{x:Math.floor((clientX-r.left)/r.width*project.width),y:Math.floor((clientY-r.top)/r.height*project.height)}}
async function act(x,y){if(x<0||y<0||x>=project.width||y>=project.height)return;let map=occupied(),k=key(x,y),i=map.get(k);if(i==null){toast('No cross stitch here');return}if(colorPick){selectColor(i);colorPick=false;$('#colorPicker').classList.remove('on');return}if(mode==='mark'){history.push([...progress.completed]);let set=new Set(progress.completed);set.has(k)?set.delete(k):set.add(k);progress.completed=[...set]}else if(mode==='park'){progress.parked[k]==null?progress.parked[k]=i:delete progress.parked[k]}else if(mode==='note'){let text=prompt('Note for this stitch:',progress.notes[k]||'');if(text!==null){text.trim()?progress.notes[k]=text.trim():delete progress.notes[k]}}await save();render();updateStatus()}
async function actRun(run){history.push([...progress.completed]);let set=new Set(progress.completed),cells=[];for(let x=run.start;x<=run.end;x++)cells.push(key(x,run.y));let remove=cells.every(k=>set.has(k));for(let k of cells)remove?set.delete(k):set.add(k);progress.completed=[...set];await save();render();updateStatus();toast(`${remove?'Unmarked':'Marked'} ${run.length} stitches in this run`)}
function updateStatus(){let total=occupied().size,done=progress.completed.length,pct=total?Math.round(done/total*100):0;$('#percent').textContent=pct+'%';$('#counts').textContent=`${done.toLocaleString()} of ${total.toLocaleString()} · ${(total-done).toLocaleString()} left`;let color=$('#colorStatus');if(selected==null){color.hidden=true}else{let p=project.palette[selected];color.hidden=false;color.innerHTML=`<i style="background:${p?.color||'#f0f'}"></i>${escapeHtml(p?.label||'Selected')} · tap a number to mark its run`}}
function selectColor(i){selected=selected===i?null:i;colorPick=false;$('#colorPicker').classList.remove('on');colorPanelOpen=selected!=null&&innerWidth>=800;render();drawPalette();updateStatus()}
function drawPalette(){$('#palette').innerHTML=project.palette.map(p=>`<button class="thread ${selected===p.index?'on':''}" data-i="${p.index}"><span class="paletteSymbol">${escapeHtml(symbolFor(p.index))}</span><span class="sw" style="background:${p.color}"></span><span><b>${escapeHtml(p.label)}</b><br>${project.full.filter(s=>s[2]===p.index).length.toLocaleString()} crosses</span></button>`).join('');document.querySelectorAll('.thread').forEach(e=>e.onclick=()=>selectColor(+e.dataset.i));$('#palette').classList.toggle('open',colorPanelOpen)}

$('#file').onchange=e=>e.target.files[0]&&importFile(e.target.files[0]);$('#fit').onclick=fit;$('#clearColor').onclick=()=>{selected=null;colorPick=false;$('#colorPicker').classList.remove('on');render();drawPalette();updateStatus()};$('#undo').onclick=async()=>{if(history.length){progress.completed=history.pop();await save();render();updateStatus()}};$('#homeBtn').onclick=goHome;$('#libraryBtn').onclick=()=>$('#library').showModal();
$('#demo').onclick=async()=>{let button=$('#demo'),label=button.textContent;button.disabled=true;button.textContent='Opening bunny…';try{let saved=bestBunny(await all());if(saved){project=saved.pattern;progress=saved.progress;xsdBytes=saved.xsdBytes||null;normalise();openWorkspace();return}let response=await fetch(new URL('demo/stitchy-bunny.stitchy.zip',location.href),{cache:'no-store'});if(!response.ok)throw Error(`Bunny demo could not load (${response.status})`);await importFile(new File([await response.blob()],'stitchy-bunny.stitchy.zip'))}catch(e){toast(e.message||'Bunny demo could not open')}finally{button.disabled=false;button.textContent=label}};
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{if(b.dataset.tool==='mark'&&mode==='mark'){mode='pan';document.querySelectorAll('[data-tool]').forEach(x=>{x.classList.remove('on');x.setAttribute('aria-pressed','false')});toast('Marking is off. Pan and zoom without changing stitches.');return}mode=b.dataset.tool;document.querySelectorAll('[data-tool]').forEach(x=>{let on=x===b;x.classList.toggle('on',on);x.setAttribute('aria-pressed',on)});if(mode==='park')toast('Park thread remembers where you left a working thread so you can return later.')});
$('#colorPicker').onclick=()=>{colorPanelOpen=!colorPanelOpen;colorPick=colorPanelOpen;$('#colorPicker').classList.toggle('on',colorPanelOpen);drawPalette();if(colorPanelOpen)toast('Choose a palette color or tap one stitch. Marking stays available afterward.')};
$('#symbolsToggle').onclick=()=>{showSymbols=!showSymbols;$('#symbolsToggle').classList.toggle('on',showSymbols);$('#symbolsToggle').setAttribute('aria-pressed',showSymbols);render()};
$('#backToggle').onclick=()=>{showBackstitch=!showBackstitch;$('#backToggle').classList.toggle('on',showBackstitch);$('#backToggle').setAttribute('aria-pressed',showBackstitch);render()};
$('#export').onclick=()=>{let name=(project.metadata?.title||'pattern')+'.xsd',manifest=JSON.stringify({format:'stitchy-project',version:1,pattern:name,progress:'progress.json'}),files={'manifest.json':manifest,'pattern.json':JSON.stringify(project),'progress.json':JSON.stringify(progress)};if(xsdBytes)files['pattern.xsd']=xsdBytes;let blob=zip(files),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(project.metadata?.title||'Stitchy')+'.stitchy.zip';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('#session').onclick=async()=>{if(!session){session={start:Date.now()};document.body.classList.add('session');navigator.wakeLock?.request('screen').then(x=>session&&(session.lock=x)).catch(()=>{});$('#session').textContent='End session';session.timer=setInterval(()=>{$('#clock').textContent=new Date(Date.now()-session.start).toISOString().slice(11,19)},1000)}else{clearInterval(session.timer);session.lock?.release();session=null;document.body.classList.remove('session');$('#session').textContent='Stitch mode';$('#clock').textContent=''}};
let v=$('#viewport');v.onpointerdown=e=>{v.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false});if(pointers.size===2){for(let p of pointers.values())p.moved=true;let p=[...pointers.values()];gesture={distance:Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y),scale,tx,ty,cx:(p[0].x+p[1].x)/2,cy:(p[0].y+p[1].y)/2}}};v.onpointermove=e=>{if(!pointers.has(e.pointerId))return;let point=pointers.get(e.pointerId),old={x:point.x,y:point.y};point.x=e.clientX;point.y=e.clientY;if(Math.hypot(point.x-point.startX,point.y-point.startY)>=8)point.moved=true;if(pointers.size===2&&gesture){for(let p of pointers.values())p.moved=true;let p=[...pointers.values()],ratio=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y)/gesture.distance,next=Math.max(.15,Math.min(8,gesture.scale*ratio));tx=gesture.cx-(gesture.cx-gesture.tx)*next/gesture.scale;ty=gesture.cy-(gesture.cy-gesture.ty)*next/gesture.scale;scale=next;render()}else if(pointers.size===1){tx+=e.clientX-old.x;ty+=e.clientY-old.y;render()}};v.onpointerup=e=>{let point=pointers.get(e.pointerId);if(pointers.size===1&&point&&!point.moved&&mode!=='pan'){let run=mode==='mark'&&runBadgeAt(e.clientX,e.clientY);if(run)actRun(run);else{let p=chartCell(e.clientX,e.clientY);act(p.x,p.y)}}pointers.delete(e.pointerId);if(pointers.size<2)gesture=null};v.onpointercancel=e=>{pointers.delete(e.pointerId);gesture=null};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');drawLibrary();
